name: cricketfantasy
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  image_picker: ^0.8.4+8
  provider: ^6.0.2
  url_launcher: ^6.0.20
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.13
  flutter_icons: ^1.1.0
  hive: ^2.0.5
  line_icons: ^2.0.1
  fluttertoast: ^8.0.8
  share:
  uuid: ^3.0.5
  sticky_headers: ^0.2.0
  percent_indicator: ^4.0.0
  cached_network_image: ^3.2.0
  page_indicator: ^0.4.1
  country_pickers: ^2.0.0
  font_awesome_flutter: ^9.2.0
  bottom_navy_bar: ^6.0.0
  webview_flutter: ^3.0.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: ^1.11.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand_medium.ttf
          style: normal
        - asset: assets/fonts/quicksand_bold.otf
          weight: 700